project_id = "kmmfltyphwtaillshbed"

[functions.analyze-disease]
enabled = true
verify_jwt = false

[functions.get-weather]
enabled = true
verify_jwt = false

[functions.create-notification]
enabled = true
verify_jwt = false